export const FLIGHT_LIST_FAIL='FLIGHT_LIST_FAIL'
export const FLIGHT_LIST_SUCCESS='FLIGHT_LIST_SUCCESS'
export const FLIGHT_LIST_REQUEST='FLIGHT_LIST_REQUEST'

export const FLIGHT_DETAILS_FAIL='FLIGHT_DETAILS_FAIL'
export const FLIGHT_DETAILS_SUCCESS='FLIGHT_DETAILS_SUCCESS'
export const FLIGHT_DETAILS_REQUEST='FLIGHT_DETAILS_REQUEST'
