# Generated by Django 4.1.7 on 2023-09-08 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_bookticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookticket',
            name='flight',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_seats', to='base.flight'),
        ),
    ]
